<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CookingAssist\Module'                        => __DIR__ . '/Module.php',
    'CookingAssist\Controller\CookingAssistController' => __DIR__ . '/src/CookingAssist/Controller/CookingAssistController.php',
    'CookingAssistTest\Framework\TestCase'        => __DIR__ . '/tests/CookingAssist/Framework/TestCase.php',
    'CookingAssistTest\SampleTest'                => __DIR__ . '/tests/CookingAssist/SampleTest.php',
);
