<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Recipe\Module'                        => __DIR__ . '/Module.php',
    'Recipe\Controller\RecipeController' => __DIR__ . '/src/Recipe/Controller/RecipeController.php',
    'RecipeTest\Framework\TestCase'        => __DIR__ . '/tests/Recipe/Framework/TestCase.php',
    'RecipeTest\SampleTest'                => __DIR__ . '/tests/Recipe/SampleTest.php',
);
