<?php

$title = 'Neues Rezept hinzufügen';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

 $form->prepare();

 echo $this->form()->openTag($form);
 //echo $this->formHidden($form->get('id'));

 echo $this->formRow($form->get('Id'));
 echo $this->formRow($form->get('Title'));
 echo $this->formRow($form->get('NoOfPeople'));
 echo $this->formRow($form->get('Kcal'));
 echo $this->formRow($form->get('PublicFlag'));
 echo $this->formRow($form->get('PreparationTime'));
 echo $this->formRow($form->get('CookingTime'));
 echo $this->formRow($form->get('RestingTime'));
 echo $this->formRow($form->get('TypeId'));
 echo $this->formRow($form->get('Level'));
 
 // Add steps
  // redundant code -> check AddRecipeForm
 $maxNumberOfSteps = $form->getMaxNumberOfSteps();;
 $initialSteps = $form->getInitialSteps();
 
 for($i=0;$i<$maxNumberOfSteps;++$i){
     ?><div id="Step<?php echo $i?>">
      <?php
     echo $this->formRow($form->get('StepQuantityValue'.$i));
     echo $this->formRow($form->get('StepUnit'.$i));
     echo $this->formRow($form->get('StepIngredient'.$i));
     echo $this->formRow($form->get('StepText'.$i));
     ?>
     </div>
      <?php   
 }

 echo $this->formRow($form->get('StepNumber'));

 echo $this->formRow($form->get('Tipp'));
 echo $this->formSubmit($form->get('Submit'));
 
 echo $this->form()->closeTag();
 
 ?>
 

 
 <script>
 window.onload = show(2);
 function show(noOfVisibleSteps) {
	 var i = 0;
	 var currentStep = document.getElementById('Step'+i);
	 while (currentStep != null){
		 if (i<noOfVisibleSteps){
			 currentStep.style.display = "block";
		 }
		 else{
			 currentStep.style.display = "none";
		 }
		 ++i;
		 currentStep = document.getElementById('Step'+i);
	 }

	 // Make sure the current number of steps is selected in drop down
	 var stepSelect = document.getElementById('NoOfStepSelect');
	 stepSelect.options[noOfVisibleSteps-1].selected = true;
}


</script>