<?php

$title = 'Neues Rezept hinzufügen';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

 $form->prepare();

 echo $this->form()->openTag($form);
 //echo $this->formHidden($form->get('id'));
 //echo $this->formRow($form->get('title'));
//  echo $this->formcollection($form);
  echo $this->formSubmit($form->get('submit'));
 
 

 
 
 echo $this->form()->closeTag();
 
 
 ?>
 

 
 <script>

 function show() {
	 var noOfStepSelect = document.getElementById('noOfStepSelect');
	 var selectedIndex = noOfStepSelect.selectedIndex;
	 var noOfVisibleSteps = Number(noOfStepSelect.options[selectedIndex].value)+1;
	 alert(noOfVisibleSteps);


	 for (i=0; i<noOfVisibleSteps; ++i){
		 document.getElementById('stepQuantity'+i).style.visibility = "visible";
		 document.getElementById('stepUnit'+i).style.visibility = "visible";
		 document.getElementById('stepIngredient'+i).style.visibility = "visible";
		 document.getElementById('stepText'+i).style.visibility = "visible";
		 alert(i);
	 }
	 for (i=noOfVisibleSteps; i<20; ++i){
		 document.getElementById('stepQuantity'+i).style.visibility = "hidden";
		 document.getElementById('stepUnit'+i).style.visibility = "hidden";
		 document.getElementById('stepIngredient'+i).style.visibility = "hidden";
		 document.getElementById('stepText'+i).style.visibility = "hidden";
	 }
}


</script>