<?php

$title = 'Neues Rezept hinzufügen';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

 $form->prepare();

 echo $this->form()->openTag($form);
 //echo $this->formHidden($form->get('id'));

 echo $this->formRow($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('tipp'));
 echo $this->formRow($form->get('noOfPeople'));
 echo $this->formRow($form->get('kcal'));
 echo $this->formRow($form->get('publicFlag'));
 echo $this->formRow($form->get('typeId'));
 echo $this->formRow($form->get('level'));
 
 // Add steps
  // redundant code -> check AddRecipeForm
 $maxNumberOfSteps = 6;
 $initialSteps = 2;
 
 for($i=0;$i<$maxNumberOfSteps;++$i){
     ?><div id="step<?php echo $i?>">
      <?php
     echo $this->formRow($form->get('stepQuantity'.$i));
     echo $this->formRow($form->get('stepUnit'.$i));
     echo $this->formRow($form->get('stepIngredient'.$i));
     echo $this->formRow($form->get('stepText'.$i));
     ?>
     </div>
      <?php   
 }

 echo $this->formRow($form->get('stepNumber'));
 echo $this->formSubmit($form->get('submit'));
 
 echo $this->form()->closeTag();
 
 
 ?>
 

 
 <script>
 window.onload = show(2);
 function show(noOfVisibleSteps) {
	 alert(noOfVisibleSteps);
	 var i = 0;
	 var currentStep = document.getElementById('step'+i);
	 while (currentStep != null){
		 if (i<noOfVisibleSteps){
// 			 currentStep.style.visibility = "visible";
			 currentStep.style.display = "block";
		 }
		 else{
// 			 currentStep.style.visibility = "hidden";
			 currentStep.style.display = "none";
		 }
		 ++i;
		 currentStep = document.getElementById('step'+i);
	 }
		   
}


</script>